### ISSUE TITLE
I can't find the resnet network implementation

### ISSUE THREAD

**Issue by wangsun** [moberweger/deep-prior-pp#11]

**Comment by moberweger** [comment]
You can check `src/net/resnet.py` if this is what you are looking for.

**Comment by wangsun** [comment]
thanks for your reply very. I can't find where to use ResNet

**Comment by moberweger** [comment]
For testing, `ResNet` is used in e.g. `src/test_realtimepipeline.py` , for training check the `src/main_*_posereg_embeddin.py` files, where you might have to replace `PoseRegNet` with `ResNet`.

**Comment by wangsun** [comment]
thanks for your reply very.I met something confusing after reading the code,in the file main_nyu_posereg_embedding.py line 118
poseNetParams = PoseRegNetParams(type=0, nChan=nChannels, wIn=imgSizeW, hIn=imgSizeH, batchSize=batchSize,numJoints=1, nDims=train_gt3D_embed.shape[1])
why you set numJoints=1 and set nDims = 30 why numJoints not 14?

**Comment by moberweger** [comment]
If you read the paper, we use a low-dimensional embedding for the pose. Therefore, the pose is a 1x30 vector and not the 14x3 3D joint locations.

**Comment by wangsun** [comment]
sorry.Maybe,I not have fully understand the article. Can you give me some guidance?or some information.emai  wangxjtuse@gmail.com  Thx

**Comment by wangsun** [comment]
I read some articles about hand pose estimation. The network is relatively shallow. Why not use the existing network? For example, ResNet101. Looking forward to your reply

**Comment by moberweger** [comment]
@wangsun 
Actually, we use ResNet50, which still runs in realtime.
