### ISSUE TITLE
Find one mistake in main_msra15_com_refine.py

### ISSUE THREAD

**Issue by buaafish** [moberweger/deep-prior-pp#13]
main_msra15_com_refine.py line: 86

`trainSeqs = [Seq0_1, Seq0_2, Seq1_1, Seq1_2, Seq2_1, Seq2_2, Seq3_1, Seq3_2,
                 Seq4_1, Seq4_2, Seq5_1, Seq5_2, Seq6_1, Seq6_1, Seq7_1, Seq7_2,
Seq8_1, Seq8_2]`

I think it should be "**Seq6_1, Seq6_2**"

**Comment by moberweger** [comment]
@buaafish Thanks! Fixed in latest commit.
