### ISSUE TITLE
Train msra15 PoseRegNetParams(type=0......

### ISSUE THREAD

**Issue by buaafish** [moberweger/deep-prior-pp#14]
I trained msra15 dataset using main_msra15_posereg_embedding_crossval.py
In line 135,  `PoseRegNetParams(type=0`, type is '0'.

But why when I used the trained model, the type should be '11'?

Thanks!

**Comment by moberweger** [comment]
For training the model, the prior layer is not included in the model type=0, and added later for inference. The model type=11 includes this prior layer and it is easier to use for inference.
