### ISSUE TITLE
The error about "ImportError: Skipping parameter for convW0!"

### ISSUE THREAD

**Issue by impet14** [moberweger/deep-prior-pp#15]
First of all, Thank you very much for the great contribution.  Could you help me with my error?
I have tried to use MSRA15 dataset for testing and use MSRA_network_prior_0.pkl and net_MSRA15_COM_AUGMENT.pkl for evaluating. Then I got the error as follow : 
`
Using gpu device 0: GeForce GTX 850M (CNMeM is disabled, cuDNN 5110)
/home/john/worksp/deep-prior-pp/src/net/convpoollayer.py:261: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  pooled_out = pool_2d(input=conv_out, ds=poolsize, ignore_border=True, mode='max')
Loading model parameters from ./eval/MSRA_network_prior_0.pkl
Possibly not matching network configuration!
......
.....
......
Traceback (most recent call last):
  File "test_realtimepipeline.py", line 81, in <module>
    rtp.processVideo(dev)
  File "/home/john/worksp/deep-prior-pp/src/util/realtimehandposepipeline.py", line 248, in processVideo
    self.initNets()
  File "/home/john/worksp/deep-prior-pp/src/util/realtimehandposepipeline.py", line 121, in initNets
    self.poseNet = ResNet(numpy.random.RandomState(23455), cfgParams=self.poseNet)
  File "/home/john/worksp/deep-prior-pp/src/net/resnet.py", line 340, in __init__
    self.load(self.cfgParams.loadFile)
  File "/home/john/worksp/deep-prior-pp/src/net/netbase.py", line 474, in load
    raise ImportError("Skipping parameter for {}! Shape {} does not fit {}.".format(p.name, p.get_value().shape, v.shape))
ImportError: Skipping parameter for convW0! Shape (32, 1, 5, 5) does not fit (8, 1, 5, 5).
`
Or anyone found the error same to mine, how do you solve it?
I use theano 0.9.0, cuda 7.5, cudnn 5.1. 
Thank you very much. Sincerely,

**Comment by moberweger** [comment]
Hi @impet14 
For MSRA, could you try `PoseRegNet` with `type=11` instead of `ResNet`? The pretrained model could be for a different network.

**Comment by impet14** [comment]
Thank you very much.
