### ISSUE TITLE
Left or right hand detection

### ISSUE THREAD

**Issue by MzXuan** [moberweger/deep-prior-pp#16]
Hello, thanks for your code.

I am now trying to use the pre-trained NYU model to track hand's posture from Realsense camera. It seems the code works well on the right hand but does not fit left hand. 
Is there any setting I miss? 
Thank you very much.

The result is shown below:
![image2](https://user-images.githubusercontent.com/13446254/41417844-0c690438-7021-11e8-8748-8c2df958c1e9.png)
![image5](https://user-images.githubusercontent.com/13446254/41417855-1293e472-7021-11e8-962d-4b153566fc0b.png)

**Comment by moberweger** [comment]
I assume you are using the realtime pipeline. In that case you have to
press 'h' to switch fro left to right hand

MzXuan <notifications@github.com> schrieb am Do., 14. Juni 2018 8:22 vorm.:

**Comment by MzXuan** [comment]
Thanks! That's exactly what I asked for.
