### ISSUE TITLE
Can this code run on Kinect v1?

### ISSUE THREAD

**Issue by qhykwsw** [moberweger/deep-prior-pp#17]
Hi, thank you for your research. I want to run your code on my own computer. My OS is Ubuntu 14.04 and camera is kinect v1. Does your code fit this camera or must be used with Creative Senz3D?

**Comment by moberweger** [comment]
Essentially it does run with kinect, but you need to do some modifications
in the realtime pipeline and add the camera device for kinect.

qianhongyi <notifications@github.com> schrieb am So., 17. Juni 2018 9:23
nachm.:

**Comment by qhykwsw** [comment]
Thank you so much for your advice. I read your code and changed "dev = CreativeCameraDevice(mirror=True)" to "dev = DepthSenseCameraDevice(mirror=True)" to use kinect v1. However, I got the error as follows:

NYUImporter_test_1_None_False_gt_300__cache.pkl
Create producer process...
Create consumer process...
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hyqian/projects/deep-prior-pp/src/util/realtimehandposepipeline.py", line 139, in threadProducer
    device.start()
  File "/home/hyqian/projects/deep-prior-pp/src/util/cameradevice.py", line 282, in start
    self.ctx = openni.Context()
AttributeError: 'module' object has no attribute 'Context'

I have install OpenNI 1.0 for kinect. Can you give me some advices? I really appreciate it.

**Comment by moberweger** [comment]
Great to hear. Did you check some examples for openni? Probably the api
changed.

qianhongyi <notifications@github.com> schrieb am So., 24. Juni 2018 2:26
vorm.:

**Comment by qhykwsw** [comment]
Actually, the OpenNI for Kinect only has C++ API and I could run the examples such as the NiViewer. I installed the python module "openni" by "pip2 install openni --user", and I found the module's version is "2.2.0.post6". I did some google search and found that the module is only for OpenNI2 instead of OpenNI1.

**Comment by qhykwsw** [comment]
Hi, Because I don't want to reinstall OpenNI to the 2nd version. So I installed the "OpenKinect/libfreenect" for Kinect v1 to use the python API to collect the depth image. Then I did some modifications in the realtime pipeline and add the camera device for kinect and finally I made it. 
Thanks for your advices and patience.

**Comment by moberweger** [comment]
That is nice. Great to hear that :)

qianhongyi <notifications@github.com> schrieb am Mo., 25. Juni 2018 12:47
vorm.:

**Comment by qhykwsw** [comment]
Sorry to bother you again. I found that if I use the orgin picture from the kinect the result will be bad. The system could't detect my hand and regress the keypoints with a little wave. Do I need do some pretreatments on the orgin picture?

**Comment by moberweger** [comment]
The hand detection should work with any camera (closest object to camera). Did
you set the camera intrinsics in the main file?
The other parts are trained from data and thus resemble the sensor noise.
For kinect v1, the NYU dataset should have the closest camera specs.

qianhongyi <notifications@github.com> schrieb am Di., 26. Juni 2018 3:46
vorm.:

**Comment by qhykwsw** [comment]
I truly used the NYU dataset. I read your code and found the "getDepthIntrinsics()" function in the file named "cameradevice.py", but I also found that the object "DepthSenseCameraDevice" for kinect doesn't use the camera intrinsics. And I also observed the output of the depth information, it's already a (480, 640) numpy matrix so it seemed that it doesn't need to use the camera intrinsics.

**Comment by moberweger** [comment]
The intrinsics should be specified in the main file as fx and fy. It is
used for the hand detector.

qianhongyi <notifications@github.com> schrieb am Di., 26. Juni 2018 7:14
vorm.:

**Comment by qhykwsw** [comment]
Do you mean the "config = {'fx': 588., 'fy': 587., 'cube': (300, 300, 300)}" in the test_realtimepipeline.py?

**Comment by moberweger** [comment]
Yes, fx and fy depend on your camera.

qianhongyi <notifications@github.com> schrieb am Di., 26. Juni 2018 7:10
nachm.:

**Comment by qhykwsw** [comment]
Oh, I originally thought that all kinect v1 has the same intrinsics. I will do some search to find them, thank you.
