### ISSUE TITLE
change the nunber of joint 

### ISSUE THREAD

**Issue by mbmamin1996** [moberweger/deep-prior-pp#20]
hi 
in your code how in can change the number of joints ??
tanks for sharing your code

**Comment by moberweger** [comment]
You can change the number of joints by providing a dataset with corresponding annotations. Therefore, you need to modify the importer, and the handposeevaluation.

**Comment by mbmamin1996** [comment]
thanks alot
i have another qustion please help me
when i was run a code that need the caffe2 i have this 
Traceback (most recent call last):
File "test_spatial_narrow_as_op.py", line 16, in 
from caffe2.proto import caffe2_pb2
ImportError: No module named caffe2.proto

i used python 2 and ubuntu 16
i install caffe2 but i have this error yet

**Comment by moberweger** [comment]
caffe2 is not necessary for this project. If you have a problem with caffe2, please ask your question in the appropriate forum.
