### ISSUE TITLE
Other Version for this project

### ISSUE THREAD

**Issue by moranli19** [moberweger/deep-prior-pp#21]
Is there any other version of deep-prior-pp on ubuntu16, cuda9?
(It's not convenient to implement this code on ubuntu14 and cuda7 )

**Comment by moberweger** [comment]
The code should in principle run with the latest theano+cuda9 on Ubuntu16. I therefore pushed a update that should enable this. Please check if there are still other adjustments necessary.

**Comment by moranli19** [comment]
Thanks a lot for your reply!!
And here is another problem:
When I run main_nyu_posereg_embedding.py, the errors come that it cannot find the "joint_data.mat".And in the NYU HandPose Dataset, there is no such file. 

So how can I find or generate this file?
Thanks a lot again!

**Comment by moberweger** [comment]
You need to download the NYU dataset from the link provided in the README.md and put it into the data folder. see for example #4
