### ISSUE TITLE
Pretrained ICVL model for COM

### ISSUE THREAD

**Issue by diealecel** [moberweger/deep-prior-pp#22]
Hi!

My goal is to use main_icvl_com_refine.py. How exactly do I use the pertained model? I see that the model provided (the one that is not simple) has almost 200 layers. There's a method to load the network weights (NetBase.load). However, there's no way to "load" the network architecture itself (the almost 200 layers, not the weights). How do I use net_ICVL_COM_AUGMENT.pkl with main_icvl_com_refine.py? Thank you!

**Comment by moberweger** [comment]
If I understand your question correctly, there are two ways you can use the pretrained model. (1) you can use it in the file test_realtimepipeline.py to run the model with a real camera. (2) in the file main_icvl_com_refine.py#L195 you can uncomment that line and comment the training code above to load the pretrained model and run it on the test sequences.
