### ISSUE TITLE
use icvl data 

### ISSUE THREAD

**Issue by mbmamin1996** [moberweger/deep-prior-pp#25]
hi i run the test with icvl hand data set and i have this what can i do ??
thanks for helping 

 File "/home/hand/1/src/data/importers.py", line 313, in loadSequence
    inputfile = open(trainlabels)
IOError: [Errno 2] No such file or directory: '../data/ICVL//test_seq_1.txt

the test_seq_1.txt  * how can i find that ???

thanks for helping

**Comment by moberweger** [comment]
You need to download the dataset first, and put it into `./data/ICVL/` . The ICVL dataset can be found at [https://labicvl.github.io/Datasets_Code.html](https://labicvl.github.io/Datasets_Code.html)
