### ISSUE TITLE
the code be written in tensorflow

### ISSUE THREAD

**Issue by sinewy333** [moberweger/deep-prior-pp#28]
Hi, thanks for your code sharing, but because your code is written in theano,  but I'm not familiar with it. So I want to ask if you have the code be written in tensorflow ? thank you !

**Comment by moberweger** [comment]
I do not have the code in tensorflow, but it should be easy modify. Simply
adjust the network and trainer classes.

**Comment by sinewy333** [comment]
thank you very much,I will try on your way.
