### ISSUE TITLE
Is there guide to install DepthSense SDK

### ISSUE THREAD

**Issue by momo1986** [moberweger/deep-prior-pp#30]
When I build src/util, it reports the error:

**

> [ 33%] Building CXX object CMakeFiles/_dscapture.dir/initdepthsense.cxx.o
> /fast/junyan/HandPose/deep-prior-pp/src/util/initdepthsense.cxx:36:10: fatal error: DepthSense.hxx: No such file or directory
>  #include <DepthSense.hxx>
>           ^~~~~~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/_dscapture.dir/build.make:86: recipe for target 'CMakeFiles/_dscapture.dir/initdepthsense.cxx.o' failed
> make[2]: *** [CMakeFiles/_dscapture.dir/initdepthsense.cxx.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/_dscapture.dir/all' failed
> make[1]: *** [CMakeFiles/_dscapture.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

**

Thus, I file the star for help.
It looks like I have not installed DepthSense SDK camera, is there the official guide and corresponding link for such suites?

Thanks

**Comment by moberweger** [comment]
You can install the SDK with `apt` package manager. A quick search on google leads to this [guide](https://software.intel.com/sites/products/realsense/intro/getting_started.html)
