### ISSUE TITLE
reference point(center point)

### ISSUE THREAD

**Issue by Ericjiejie** [moberweger/deep-prior-pp#33]
Hi, @moberweger
i find other authors use your network to generate reference point(center point)  to get a cubic including a hand,and you can tell me  where is the network in your code.For example ,i need reference point of MSRA dataset. What should i do

**Comment by moberweger** [comment]
Please check the file [main_msra15_com_refine.py](https://github.com/moberweger/deep-prior-pp/blob/master/src/main_msra15_com_refine.py) to see how it is done.

**Comment by Fazlik995** [comment]
@Ericjiejie 

could u get reference points? If so, could u tell how?

thanks

**Comment by Ericjiejie** [comment]
@Fazlik995
I haven't thought about it, but I think the reference point is obtained through this way, i.e. ndimage.measurements.center_of_mass("object" ) that ndimage is from scipy. You can try it.
