### ISSUE TITLE
This is some woring with the code!

### ISSUE THREAD

**Issue by xinlon-z** [moberweger/deep-prior-pp#35]
This is a error in  `deep-prior-pp/src/data/transformations.py`(line: 117):
``` python
from transforms3d.euler import euler2mat
R[:3, :3] = euler2mat(alpha_x, alpha_y, alpha_z, 'rxyz')
``` 
I cannot found the **transforms3d** in this project.
How can I fix it ?

**Comment by moberweger** [comment]
transforms3d is an 3rd party python package. On Ubuntu, use `pip install transforms3d` to install this package.

**Comment by xinlon-z** [comment]
Thanks!It's helpful.
