### ISSUE TITLE
NYU testset

### ISSUE THREAD

**Issue by ShikaiChen** [moberweger/deep-prior-pp#4]
Dear @moberweger ,
Thanks for your sharing.
I have downloaded NYU dataset, and there is only one testset.
However, in main_nyu_com_refine.py:
    Seq2_1 = di.loadSequence('test_1', docom=True)
    Seq2_2 = di.loadSequence('test_2', docom=True)
Could you please tell me where I can find test_1 and test_2.

**Comment by moberweger** [comment]
Hi, 
The NYU test set consists of 2 different users. The first 2440 frames are for 'test_1', the remaining frames are for 'test_2', so you simply have to split them into two folders.

**Comment by ShikaiChen** [comment]
@moberweger Thank you for your help！
