### ISSUE TITLE
train/test split of the msra15 dataset

### ISSUE THREAD

**Issue by laserwave** [moberweger/deep-prior-pp#47]
HI,

I wonder why “P0”  of msra15 dataset is used as both train data and test data in main_msra15_com_refine.py.

And what is the train/test split setting of the pretrained net_MSRA15_COM_AUGMENT.pkl.

**Comment by moberweger** [comment]
It is true that the "P0" sequence is used for training and testing. This is solely for improving the results for online demos (more data -> better results). For the results reported in the paper, it is of course excluded and a different randomized training scheme is used.
You can simply adjust the data to your needs (reproduce results of the paper vs. better results of a real-time demo).

**Comment by laserwave** [comment]
Thank you. I use the pretrained parameters of  MSRA15 dataset you provide to run the test_realtimepipeline.py. 
Here is the settings and results of 'P0' sequence. But the result is not good.  Is that right?

`poseNetParams = PoseRegNetParams(type=11, nChan=1, wIn=128, hIn=128, batchSize=128, numJoints=21, nDims=3)`
`poseNetParams.loadFile = "MSRA_network_prior_0.pkl"`
`comrefNetParams = ScaleNetParams(type=1, nChan=1, wIn=128, hIn=128, batchSize=1, resizeFactor=2, numJoints=1, nDims=3)`
`comrefNetParams.loadFile = "net_MSRA15_COM_AUGMENT.pkl"`
`config = {'fx': 241.42, 'fy': 241.42, 'cube': (250, 250, 250)}`
![screenshot-20221018-211805](https://user-images.githubusercontent.com/18577799/196441636-71d00d5d-77e5-4127-8078-cab265903422.png)
![screenshot-20221018-211818](https://user-images.githubusercontent.com/18577799/196441642-01f64dbd-0ebd-4903-8f43-84bd10cc401e.png)

**Comment by moberweger** [comment]
Interesting effect, thanks for sharing. It certainly does not look correct, it should work much better. Did you check 1) the networks are loaded correctly, 2) the data is in the correct format, 3) the crop for the networks is in the correct format, 4) it seems you run with "com" mode, you could try the tracking mode with refined location enabled.

**Comment by laserwave** [comment]
The result is much better from the third frame of the sequence using the tracking mode. Why the first two seem still bad and the following correct? 


![image](https://user-images.githubusercontent.com/18577799/196643884-616048fe-01e5-4721-b188-9b8b80f8945d.png)
(the third frame)

**Comment by moberweger** [comment]
Yes, that one looks much better. Possibly something is wrongly initialized? I am not sure about the details how you run it.
