### ISSUE TITLE
Could you provide more explanation about the input of the "RealtimeHandposePipeline" class

### ISSUE THREAD

**Issue by TheoCarme** [moberweger/deep-prior-pp#48]
Hello, I am sorry if I missed the information I am about to ask.
Could you give me :
- The type and shape or format of the parameters : "poseNet", "config", "di" and "comrefNet"
- If they exist in the project the names of the functions to get those parameters.

I would greatly appreciate even a partial answer.
Thank you in advance.

**Comment by moberweger** [comment]
Please take a look at test_realtimepipeline.py
poseNet is the trained neural network, config is a dictionary with
configuration parameters, di is the data importer object for loading
images, and comrefnet is the refinement network for the hand location. All
these are defined in the test file.
