### ISSUE TITLE
MSRA also training and testing on P0?

### ISSUE THREAD

**Issue by npow** [moberweger/deep-prior-pp#5]
I'm probably misreading the code, but it seems like you are training and testing on P0?

https://github.com/moberweger/deep-prior-pp/blob/master/src/main_msra15_com_refine.py#L52

**Comment by moberweger** [comment]
You are correct that this script trains and tests on P0. However, this is only a demo code. 

For the results in the paper we used cross validation, where we test on one user and train on the remaining users. We repeat this for all users and report the average over all these runs.

**Comment by npow** [comment]
Thanks for clarifying!

**Comment by ivicts** [comment]
Hi, I know you are using cross validation for the real hand pose estimation in MSRA dataset. But, for the refinement step are you also using the cross validation? So, for user P0, the refinement network is trained using network trained using P1 until P8? So, there are nine different refinement networks for MSRA? Or it is only one as in the repo?

Furthermore, may I know what's the reason to include both training sequence using docom=True and docom=False, is it just to enlarge the training set for the refinement network?

**Comment by moberweger** [comment]
@ivicts there is only one published, but there is one for each fold of the cross validation.
Yes, the two docom are used to create a larger training set.
