### ISSUE TITLE
PreTrained MSRA model

### ISSUE THREAD

**Issue by buaafish** [moberweger/deep-prior-pp#6]
Hi, @moberweger 

Thanks for sharing your work.
I have read your papers and run your project.  You already released pretrained models for ICVL and NYU dataset.  In your models, there is MSRA_network_prior_0.pkl. This model cannot load in your project. I found this model just have 13 layers. And its size just have 7.9MB.

Can you tell me how to use this model? I want to test your method in MSRA dataset.

Sincerely yours

**Comment by moberweger** [comment]
Hi,
this pretrained model is for the small network configuration. It should load with `PoseRegNetParams type=11` in main_msra15_posereg_embedding_crossval.py . The  `_0` means it is for the first fold of the the cross-validation, ie test on P0.
If you still get an error, please post it here.
