### ISSUE TITLE
The com parameter in cropArea3D function

### ISSUE THREAD

**Issue by LuciaXu** [moberweger/deep-prior-pp#7]
Hi, @moberweger 
Thank you for sharing your great work.
I'm a little confused about the com parameter in cropArea3D function. If I'm not mistaken, it is the center of mass, around which the cube is cropped. But in loadSequence function of Importer (1017 line), the center joint position is passed as the com parameter. It seems a bit difference with what you've done in the paper, which use the center of mass of depth to segment hand.
Since I'd like to follow what you've done in the paper, should I do the cropping like this:
`com,size=hd.detect(size=config['cube'])`
`dpt, M, com = hd.cropArea3D(com=com, size=config['cube'])`

**Comment by moberweger** [comment]
Hi, 
The com parameter is the center of the hand (metacarpophalangeal joint). The center joint position as you mention is passed for debug purpose. What you have to do to follow the pipeline of the paper is to pass `refineNet` to the constructor of the Importer, and then pass `docom=True` to the `loadSequence` function. 

`docom=True` calculates the center of mass, and the `refineNet` parameter (string with path to saved refinement network) calculates the refined location of the hand.
