### ISSUE TITLE
Requirements: CUDA and cuDNN versions?

### ISSUE THREAD

**Issue by VassilisCN** [moberweger/deep-prior-pp#9]
Hello,
In your README file you state that CUDA 7 + cuDNN 5  is required. However, in NVIDIA's site https://developer.nvidia.com/rdp/cudnn-archive I only find these two alternatives 
Download cuDNN v5 (May 27, 2016), for CUDA 8.0
Download cuDNN v5 (May 12, 2016), for CUDA 7.5 
Is it perhaps the case that you mean cuDNN 5 on CUDA 7.5?

Thanks in advance,
best regards,
Vassilis

**Comment by moberweger** [comment]
Yes, back then I used CUDA 7 + cuDNN 5, but you can also try newer version. CUDA 7.5 should work fine as well. There are only some incompatibilities of theano + CUDA that you should consider.

**Comment by VassilisCN** [comment]
So far so good with CUDA 7.5 and cuDNN 5

Thanks again!
